### ISSUE TITLE
Cant start Bot

### ISSUE THREAD

**Issue by albertusQuelle** [vzemtsov/ssh-Connection-In-Telegram#8]
Hey, i get 
`python bot.py
  File "bot.py", line 253
    while True
             ^
SyntaxError: invalid syntax
`

could you help me?

**Comment by nicolashenriquez** [comment]
Hello,
I think you have to add ":" after while True
while True:
    if __name__ == '__main__':
        bot.polling(none_stop=True)
    time.sleep(10)
